import Link from "next/link";

type Props = {
  params: {
    id: string;
  };
};

// 동적인 메타데이타 메소드
export const generateMetadata = ({ params }: Props) => {
  return {
    title: "안녕 About Page 야", // 주소창 title
    description: "Generated by create next app",
  };
};

const AboutPage = () => {
  return (
    <div className="">
      <div>
        <Link href={"/about2"}>go about2</Link>
      </div>
      <div>
        <Link href={"/"}>go home</Link>
      </div>
    </div>
  );
};

export default AboutPage;
